name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
commitish: 'main'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '⚠️ Breaking Changes'
    labels:
      - 'breaking'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'pom'
  - title: '⬆️ Dependency upgrades'
    labels:
      - 'bump'
      - 'dependencies'
template: |
  ## What's Changed
  $CHANGES
