name: Publish release
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'maven'
      - name: Publish artifact
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: x-access-token
        run: |
          mvn -B versions:set -DnewVersion=${NEW_VERSION}
          mvn -B clean deploy
